### ISSUE TITLE
Add barebones implementation for `ahkpm install github.com/user/repo`

### ISSUE THREAD

**Issue by joshuacc** [joshuacc/ahkpm#6]
Running `ahkpm install github.com/user/repo` should do the following:

1. Attempt to download the tarball from the repo (from the main/master branch)
2. If successful, extract it into `ahkpm_libs`
3. If successful, record it into `ahkpm.json` as `"github.com/user/repo": "${branch/commit identifier}"`

**Open question:** What version identifier should we use by default? Branch name? Then things may break when the branch is updated. Specific commit? It won't change, but it's pretty inscrutable. Tag name? Seems reasonable, but would require either decent knowledge of git by the user or adherence to a naming/versioning convention by library authors.

We might be able to get adherence to a convention, but that would be a long slow slog of evangelizing ahkpm to AHK library authors.

**TODO:**

- [x] Scaffold command
- [x] Save results to ahkpm.json
- [x] Support `tag:` version identifiers
- [x] Support `branch:` version identifiers
- [x] Support `commit:` version identifiers
- [x] Support exact SemVer version identifiers

**Defer to future version**
- Support omitting version identifiers
- Support version ranges/shorthands

**Comment by joshuacc** [comment]
Will follow the example set by Go and Bower. If a version (rather than a commit, tag, or branch name) is specified, we will look for a tag matching that version.

**Comment by joshuacc** [comment]
Version identifiers can be one of the following:

- A valid semantic version according to semver.org
- The string "tag:" followed by the name of a git tag, like `tag:beta2`
- The string "branch:" followed by the name of a git branch, like `branch:main`
- The string "commit:" followed by a git commit hash, like `commit:d9876f2abdb184d7461d496f1455fd2e1db7089c`

**Comment by joshuacc** [comment]
Done
